### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by samTime101** [baribgf/Py-Exe-Project#1]
Hello i am samip please help me to compile my Python file to exe

```
 ________________________
| Welcome to PyExe v1.0  |
| Developed by: Bari BGF |
| [\q] -> Quit           |
|________________________|

> Python main file path: ./main.py
> Out exe name [Return for original]: 
> Do you want to compile the full project? [Return for YES]: 

Please wait /workspaces/Py-Exe-Project/./src/pyexe/main.cpp:10:21: error: ‘filesystem’ is not a namespace-name
   10 | namespace fs = std::filesystem;
      |                     ^~~~~~~~~~
/workspaces/Py-Exe-Project/./src/pyexe/main.cpp: In function ‘int main(int, const char**)’:
/workspaces/Py-Exe-Project/./src/pyexe/main.cpp:14:5: error: ‘fs’ has not been declared
   14 |     fs::path thisPath = argv[0];
      |     ^~
/workspaces/Py-Exe-Project/./src/pyexe/main.cpp:15:5: error: ‘fs’ has not been declared
   15 |     fs::path thisSpace = thisPath.parent_path();
      |     ^~
/workspaces/Py-Exe-Project/./src/pyexe/main.cpp:19:32: error: ‘thisSpace’ was not declared in this scope; did you mean ‘isspace’?
   19 |     temp_status = chdir(string(thisSpace).c_str());
      |                                ^~~~~~~~~
      |                                isspace
Please wait Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'Cython'
          Traceback (most recent call last):
  File "/workspaces/Py-Exe-Project/src/pyexe/package_compiler.py", line 37, in compile_package
    copytree(package_path, new_package_path)
  File "/usr/local/python/3.10.8/lib/python3.10/shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/python/3.10.8/lib/python3.10/shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/local/python/3.10.8/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/workspaces/Py-Exe-Project-compiled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/Py-Exe-Project/./src/pyexe/main.py", line 163, in <module>
    compile_package(os.path.abspath(os.path.dirname(MAIN_PY_PATH)), exclude=[os.path.basename(MAIN_PY_PATH)])
  File "/workspaces/Py-Exe-Project/src/pyexe/package_compiler.py", line 40, in compile_package
    return compile_package(package_path, exclude)
  File "/workspaces/Py-Exe-Project/src/pyexe/package_compiler.py", line 47, in compile_package
    compile_module(module_path)
  File "/workspaces/Py-Exe-Project/src/pyexe/package_compiler.py", line 19, in compile_module
    remove("".join(module_path.split('.')[:-1]) + '.c')
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/Py-Exe-Project-compiled/src/pyexe/__init__.c'
Please wait .                         
```

**Comment by baribgf** [comment]
Hey, hope you are alright!
I think that of cause a different C++ version than 11 installed on your machine.
Just check the version and try again.

**Comment by baribgf** [comment]
Solved
